import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Translator App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full bg-gray-50'>
      <body className={`${inter.className} h-full`}>
        <Header />
        <div className="flex flex-col justify-center py-12 mx-auto max-w-7xl p-6 lg:px-8">
          {children}
        </div>
      </body>
    </html>
  )
}
